/**
 * Seed global flight data into the B2B app SQLite database.
 * Flights are shared across all organizations — only bookings are org-scoped.
 *
 * Usage:
 *   node scripts/seed-flights.js           (seed if not already seeded)
 *   node scripts/seed-flights.js --force   (reset and re-seed)
 */

import Database from "better-sqlite3";
import { existsSync, mkdirSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const schemaPath = resolve(root, "app/lib/db/schema.sql");
const dbPath = resolve(root, process.env.DB_PATH ?? "data/app.db");
const force = process.argv.includes("--force") || process.argv.includes("-f");

// ─── Flight catalog (global, shared across all orgs) ─────────────────────────

const flights = [
  // ── Economy — within typical $500 policy cap ──────────────────────────────
  {
    id: "flight-nyc-lax-01",
    from_city: "New York",
    to_city: "Los Angeles",
    airline: "Horizon Airlines",
    departure_time: "08:00",
    arrival_time: "11:30",
    duration: "5h 30m",
    stops: 0,
    price: 268,
    currency: "USD",
    cabin: "Economy",
    dates: "Jun 12 - Jun 18",
    tags: JSON.stringify(["Best value", "Nonstop"]),
  },
  {
    id: "flight-chi-mia-01",
    from_city: "Chicago",
    to_city: "Miami",
    airline: "American Air",
    departure_time: "10:15",
    arrival_time: "14:45",
    duration: "3h 30m",
    stops: 0,
    price: 245,
    currency: "USD",
    cabin: "Economy",
    dates: "Jul 04 - Jul 16",
    tags: JSON.stringify(["Nonstop", "Popular"]),
  },
  {
    id: "flight-sfo-sea-01",
    from_city: "San Francisco",
    to_city: "Seattle",
    airline: "West Coast Express",
    departure_time: "14:20",
    arrival_time: "16:10",
    duration: "2h 50m",
    stops: 0,
    price: 156,
    currency: "USD",
    cabin: "Economy",
    dates: "Aug 21 - Aug 27",
    tags: JSON.stringify(["Quick trip"]),
  },
  {
    id: "flight-bos-fll-01",
    from_city: "Boston",
    to_city: "Fort Lauderdale",
    airline: "East Coast Airways",
    departure_time: "11:45",
    arrival_time: "15:20",
    duration: "3h 35m",
    stops: 0,
    price: 224,
    currency: "USD",
    cabin: "Economy",
    dates: "Jun 20 - Jun 26",
    tags: JSON.stringify(["Beach trip"]),
  },
  {
    id: "flight-den-las-01",
    from_city: "Denver",
    to_city: "Las Vegas",
    airline: "Mountain Air",
    departure_time: "09:30",
    arrival_time: "10:45",
    duration: "2h 15m",
    stops: 0,
    price: 132,
    currency: "USD",
    cabin: "Economy",
    dates: "Jun 12 - Jun 18",
    tags: JSON.stringify(["Budget flight", "Direct"]),
  },
  {
    id: "flight-phx-nyc-01",
    from_city: "Phoenix",
    to_city: "New York",
    airline: "Horizon Airlines",
    departure_time: "13:00",
    arrival_time: "20:15",
    duration: "4h 15m",
    stops: 0,
    price: 289,
    currency: "USD",
    cabin: "Economy",
    dates: "Jun 12 - Jun 18",
    tags: JSON.stringify(["Flexible ticket", "Carry-on included"]),
  },
  {
    id: "flight-dal-msy-01",
    from_city: "Dallas",
    to_city: "New Orleans",
    airline: "Southern Sky",
    departure_time: "07:15",
    arrival_time: "09:45",
    duration: "2h 30m",
    stops: 0,
    price: 147,
    currency: "USD",
    cabin: "Economy",
    dates: "Jul 04 - Jul 16",
    tags: JSON.stringify(["Good price", "Morning"]),
  },
  {
    id: "flight-lax-san-01",
    from_city: "Los Angeles",
    to_city: "San Diego",
    airline: "SunFly",
    departure_time: "15:30",
    arrival_time: "16:20",
    duration: "1h 50m",
    stops: 0,
    price: 98,
    currency: "USD",
    cabin: "Economy",
    dates: "Sep 02 - Sep 09",
    tags: JSON.stringify(["Shortest flight", "Budget"]),
  },
  {
    id: "flight-nyc-lax-02",
    from_city: "New York",
    to_city: "Los Angeles",
    airline: "Blue Sky Airlines",
    departure_time: "20:45",
    arrival_time: "00:20",
    duration: "5h 35m",
    stops: 0,
    price: 298,
    currency: "USD",
    cabin: "Economy",
    dates: "Jun 12 - Jun 18",
    tags: JSON.stringify(["Evening", "Red-eye"]),
  },
  {
    id: "flight-sea-lax-01",
    from_city: "Seattle",
    to_city: "Los Angeles",
    airline: "Pacific Jet",
    departure_time: "06:30",
    arrival_time: "09:10",
    duration: "2h 40m",
    stops: 0,
    price: 178,
    currency: "USD",
    cabin: "Economy",
    dates: "Jul 15 - Jul 22",
    tags: JSON.stringify(["Early bird", "Nonstop"]),
  },

  // ── Additional domestic Economy flights ───────────────────────────────────
  {
    id: "flight-atl-ord-01",
    from_city: "Atlanta",
    to_city: "Chicago",
    airline: "Southern Sky",
    departure_time: "06:45",
    arrival_time: "08:15",
    duration: "1h 30m",
    stops: 0,
    price: 189,
    currency: "USD",
    cabin: "Economy",
    dates: "Jun 15 - Jun 22",
    tags: JSON.stringify(["Early bird", "Nonstop"]),
  },
  {
    id: "flight-msp-lax-01",
    from_city: "Minneapolis",
    to_city: "Los Angeles",
    airline: "North Star Air",
    departure_time: "11:30",
    arrival_time: "14:05",
    duration: "3h 35m",
    stops: 0,
    price: 214,
    currency: "USD",
    cabin: "Economy",
    dates: "Jun 28 - Jul 05",
    tags: JSON.stringify(["Nonstop"]),
  },
  {
    id: "flight-nyc-chi-01",
    from_city: "New York",
    to_city: "Chicago",
    airline: "East Coast Airways",
    departure_time: "07:00",
    arrival_time: "09:05",
    duration: "2h 05m",
    stops: 0,
    price: 172,
    currency: "USD",
    cabin: "Economy",
    dates: "Jul 01 - Jul 07",
    tags: JSON.stringify(["Morning", "Quick trip"]),
  },
  {
    id: "flight-lax-phx-01",
    from_city: "Los Angeles",
    to_city: "Phoenix",
    airline: "Desert Air",
    departure_time: "12:45",
    arrival_time: "14:10",
    duration: "1h 25m",
    stops: 0,
    price: 119,
    currency: "USD",
    cabin: "Economy",
    dates: "Jul 10 - Jul 17",
    tags: JSON.stringify(["Budget", "Short haul"]),
  },
  {
    id: "flight-hou-ord-01",
    from_city: "Houston",
    to_city: "Chicago",
    airline: "Gulf Breeze Air",
    departure_time: "09:15",
    arrival_time: "12:05",
    duration: "2h 50m",
    stops: 0,
    price: 198,
    currency: "USD",
    cabin: "Economy",
    dates: "Jul 20 - Jul 27",
    tags: JSON.stringify(["Nonstop"]),
  },
  {
    id: "flight-ord-den-01",
    from_city: "Chicago",
    to_city: "Denver",
    airline: "Horizon Airlines",
    departure_time: "14:50",
    arrival_time: "17:00",
    duration: "3h 10m",
    stops: 0,
    price: 162,
    currency: "USD",
    cabin: "Economy",
    dates: "Aug 01 - Aug 08",
    tags: JSON.stringify(["Afternoon"]),
  },
  {
    id: "flight-mia-atl-01",
    from_city: "Miami",
    to_city: "Atlanta",
    airline: "SunFly",
    departure_time: "08:30",
    arrival_time: "10:10",
    duration: "1h 40m",
    stops: 0,
    price: 143,
    currency: "USD",
    cabin: "Economy",
    dates: "Aug 05 - Aug 12",
    tags: JSON.stringify(["Morning", "Direct"]),
  },
  {
    id: "flight-pdx-sfo-01",
    from_city: "Portland",
    to_city: "San Francisco",
    airline: "West Coast Express",
    departure_time: "10:00",
    arrival_time: "11:50",
    duration: "1h 50m",
    stops: 0,
    price: 134,
    currency: "USD",
    cabin: "Economy",
    dates: "Aug 10 - Aug 17",
    tags: JSON.stringify(["Short hop", "Budget"]),
  },
  {
    id: "flight-bos-dca-01",
    from_city: "Boston",
    to_city: "Washington D.C.",
    airline: "East Coast Airways",
    departure_time: "16:20",
    arrival_time: "17:50",
    duration: "1h 30m",
    stops: 0,
    price: 127,
    currency: "USD",
    cabin: "Economy",
    dates: "Aug 15 - Aug 22",
    tags: JSON.stringify(["Quick trip", "Afternoon"]),
  },
  {
    id: "flight-las-sea-01",
    from_city: "Las Vegas",
    to_city: "Seattle",
    airline: "Pacific Jet",
    departure_time: "13:30",
    arrival_time: "15:55",
    duration: "2h 25m",
    stops: 0,
    price: 168,
    currency: "USD",
    cabin: "Economy",
    dates: "Aug 18 - Aug 25",
    tags: JSON.stringify(["Afternoon", "Nonstop"]),
  },
  {
    id: "flight-sfo-den-01",
    from_city: "San Francisco",
    to_city: "Denver",
    airline: "Mountain Air",
    departure_time: "07:45",
    arrival_time: "10:55",
    duration: "2h 10m",
    stops: 0,
    price: 185,
    currency: "USD",
    cabin: "Economy",
    dates: "Sep 05 - Sep 12",
    tags: JSON.stringify(["Early bird"]),
  },
  {
    id: "flight-dfw-jfk-01",
    from_city: "Dallas",
    to_city: "New York",
    airline: "American Air",
    departure_time: "09:00",
    arrival_time: "13:25",
    duration: "3h 25m",
    stops: 0,
    price: 241,
    currency: "USD",
    cabin: "Economy",
    dates: "Sep 08 - Sep 15",
    tags: JSON.stringify(["Morning", "Nonstop"]),
  },
  {
    id: "flight-ord-atl-01",
    from_city: "Chicago",
    to_city: "Atlanta",
    airline: "BlueSky Airlines",
    departure_time: "17:30",
    arrival_time: "20:50",
    duration: "2h 20m",
    stops: 0,
    price: 175,
    currency: "USD",
    cabin: "Economy",
    dates: "Sep 12 - Sep 19",
    tags: JSON.stringify(["Evening"]),
  },
  {
    id: "flight-phx-sea-01",
    from_city: "Phoenix",
    to_city: "Seattle",
    airline: "Desert Air",
    departure_time: "11:00",
    arrival_time: "13:50",
    duration: "2h 50m",
    stops: 0,
    price: 192,
    currency: "USD",
    cabin: "Economy",
    dates: "Sep 15 - Sep 22",
    tags: JSON.stringify(["Nonstop"]),
  },

  // ── Economy — slightly above $500 cap (approval-required territory) ────────
  {
    id: "flight-jfk-lhr-01",
    from_city: "New York",
    to_city: "London",
    airline: "TransAtlantic Airways",
    departure_time: "21:00",
    arrival_time: "09:30+1",
    duration: "8h 30m",
    stops: 0,
    price: 548,
    currency: "USD",
    cabin: "Economy",
    dates: "Aug 01 - Aug 10",
    tags: JSON.stringify(["International", "Nonstop"]),
  },
  {
    id: "flight-lax-ord-01",
    from_city: "Los Angeles",
    to_city: "Chicago",
    airline: "Horizon Airlines",
    departure_time: "11:00",
    arrival_time: "16:45",
    duration: "3h 45m",
    stops: 0,
    price: 530,
    currency: "USD",
    cabin: "Economy",
    dates: "Sep 10 - Sep 17",
    tags: JSON.stringify(["Business route"]),
  },

  // ── Premium Economy ────────────────────────────────────────────────────────
  {
    id: "flight-chi-mia-02",
    from_city: "Chicago",
    to_city: "Miami",
    airline: "Star Airways",
    departure_time: "16:00",
    arrival_time: "20:30",
    duration: "3h 30m",
    stops: 0,
    price: 420,
    currency: "USD",
    cabin: "Premium Economy",
    dates: "Oct 10 - Oct 18",
    tags: JSON.stringify(["Premium", "Nonstop"]),
  },
  {
    id: "flight-nyc-mia-01",
    from_city: "New York",
    to_city: "Miami",
    airline: "Eastern Jet",
    departure_time: "07:45",
    arrival_time: "11:05",
    duration: "3h 20m",
    stops: 0,
    price: 385,
    currency: "USD",
    cabin: "Premium Economy",
    dates: "Jun 25 - Jul 02",
    tags: JSON.stringify(["Comfortable", "Extra legroom"]),
  },
  {
    id: "flight-sfo-jfk-01",
    from_city: "San Francisco",
    to_city: "New York",
    airline: "Cross Country Air",
    departure_time: "10:30",
    arrival_time: "19:15",
    duration: "5h 45m",
    stops: 0,
    price: 620,
    currency: "USD",
    cabin: "Premium Economy",
    dates: "Jul 20 - Jul 28",
    tags: JSON.stringify(["Premium", "Transcontinental"]),
  },
  {
    id: "flight-sea-ord-pe-01",
    from_city: "Seattle",
    to_city: "Chicago",
    airline: "Pacific Jet",
    departure_time: "09:15",
    arrival_time: "15:30",
    duration: "4h 15m",
    stops: 0,
    price: 445,
    currency: "USD",
    cabin: "Premium Economy",
    dates: "Aug 03 - Aug 10",
    tags: JSON.stringify(["Extra legroom", "Nonstop"]),
  },

  // ── Business class ─────────────────────────────────────────────────────────
  {
    id: "flight-nyc-lax-biz-01",
    from_city: "New York",
    to_city: "Los Angeles",
    airline: "Executive Air",
    departure_time: "09:00",
    arrival_time: "12:30",
    duration: "5h 30m",
    stops: 0,
    price: 1450,
    currency: "USD",
    cabin: "Business",
    dates: "Jun 12 - Jun 18",
    tags: JSON.stringify(["Lie-flat", "Premium lounge"]),
  },
  {
    id: "flight-jfk-lhr-biz-01",
    from_city: "New York",
    to_city: "London",
    airline: "Global Business Jets",
    departure_time: "18:30",
    arrival_time: "06:45+1",
    duration: "8h 15m",
    stops: 0,
    price: 3200,
    currency: "USD",
    cabin: "Business",
    dates: "Aug 05 - Aug 14",
    tags: JSON.stringify(["International business", "Flat bed"]),
  },
  {
    id: "flight-chi-lax-biz-01",
    from_city: "Chicago",
    to_city: "Los Angeles",
    airline: "BlueSky Premier",
    departure_time: "07:30",
    arrival_time: "10:00",
    duration: "3h 30m",
    stops: 0,
    price: 1820,
    currency: "USD",
    cabin: "Business",
    dates: "Sep 01 - Sep 08",
    tags: JSON.stringify(["Early morning", "Business class"]),
  },
  {
    id: "flight-atl-sea-biz-01",
    from_city: "Atlanta",
    to_city: "Seattle",
    airline: "Executive Air",
    departure_time: "08:00",
    arrival_time: "11:20",
    duration: "5h 20m",
    stops: 0,
    price: 1650,
    currency: "USD",
    cabin: "Business",
    dates: "Sep 20 - Sep 27",
    tags: JSON.stringify(["Business class", "Lie-flat"]),
  },

  // ── First class ────────────────────────────────────────────────────────────
  {
    id: "flight-nyc-lax-first-01",
    from_city: "New York",
    to_city: "Los Angeles",
    airline: "Prestige Airways",
    departure_time: "10:00",
    arrival_time: "13:30",
    duration: "5h 30m",
    stops: 0,
    price: 4800,
    currency: "USD",
    cabin: "First Class",
    dates: "Jun 12 - Jun 18",
    tags: JSON.stringify(["Private suite", "Gourmet dining"]),
  },
];

// ─── Seeding ──────────────────────────────────────────────────────────────────

if (!existsSync(dirname(dbPath))) {
  mkdirSync(dirname(dbPath), { recursive: true });
}

const db = new Database(dbPath);
db.pragma("journal_mode = WAL");
db.pragma("foreign_keys = ON");
db.exec(readFileSync(schemaPath, "utf8"));

const existing = db.prepare("SELECT COUNT(*) as count FROM flights").get();
if (existing.count > 0 && !force) {
  console.log(`Flights already seeded (${existing.count} rows). Use --force to re-seed.`);
  db.close();
  process.exit(0);
}

if (force) {
  db.pragma("foreign_keys = OFF");
  db.prepare("DELETE FROM flights").run();
  db.pragma("foreign_keys = ON");
  console.log("Cleared existing flights.");
}

const insert = db.prepare(`
  INSERT OR REPLACE INTO flights
    (id, from_city, to_city, airline, departure_time, arrival_time, duration, stops, price, currency, cabin, dates, tags)
  VALUES
    (@id, @from_city, @to_city, @airline, @departure_time, @arrival_time, @duration, @stops, @price, @currency, @cabin, @dates, @tags)
`);

const seed = db.transaction(() => {
  for (const f of flights) insert.run(f);
  return flights.length;
});

const count = seed();
db.close();

console.log(`Seeded ${count} flights into ${dbPath}`);
console.log("\nFlight mix:");
console.log("  Economy (≤$300):         23 flights — in-policy for typical $500 cap");
console.log("  Economy ($530-$548):       2 flights — approval-required zone");
console.log("  Premium Economy:           4 flights — cabin upgrade, mixed prices");
console.log("  Business:                  4 flights — out-of-policy for Economy policies");
console.log("  First Class:               1 flight  — always out-of-policy");
